# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MapsVisualizer(object):
    def setupUi(self, MapsVisualizer):
        MapsVisualizer.setObjectName("MapsVisualizer")
        MapsVisualizer.resize(1000, 750)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/main/logo.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MapsVisualizer.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MapsVisualizer)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(self.frame_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.commandTabs = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandTabs.sizePolicy().hasHeightForWidth())
        self.commandTabs.setSizePolicy(sizePolicy)
        self.commandTabs.setMinimumSize(QtCore.QSize(275, 0))
        self.commandTabs.setObjectName("commandTabs")
        self.generalOptions = QtWidgets.QWidget()
        self.generalOptions.setAccessibleName("")
        self.generalOptions.setObjectName("generalOptions")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.generalOptions)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.generalOptions)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 977, 662))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_6.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_6.setHorizontalSpacing(0)
        self.gridLayout_6.setVerticalSpacing(8)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame = CollapsablePanel(self.scrollAreaWidgetContents)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_13 = CollapsablePanelHeader(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_4.addWidget(self.label_13)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.frame_3 = CollapsablePanelContent(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_3)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(6, 6, 0, 0)
        self.formLayout_2.setHorizontalSpacing(6)
        self.formLayout_2.setVerticalSpacing(3)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.general_dimension = QtWidgets.QSpinBox(self.frame_3)
        self.general_dimension.setObjectName("general_dimension")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.general_dimension)
        self.label_16 = QtWidgets.QLabel(self.frame_3)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.general_slice_index = QtWidgets.QSpinBox(self.frame_3)
        self.general_slice_index.setObjectName("general_slice_index")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.general_slice_index)
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.general_volume_index = QtWidgets.QSpinBox(self.frame_3)
        self.general_volume_index.setObjectName("general_volume_index")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.general_volume_index)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.gridLayout_6.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_4 = CollapsablePanel(self.scrollAreaWidgetContents)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_17 = CollapsablePanelHeader(self.frame_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_5.addWidget(self.label_17)
        self.line_3 = QtWidgets.QFrame(self.frame_4)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_5.addWidget(self.line_3)
        self.frame_5 = CollapsablePanelContent(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_10.setContentsMargins(6, 6, 0, 0)
        self.gridLayout_10.setHorizontalSpacing(6)
        self.gridLayout_10.setVerticalSpacing(3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_20 = QtWidgets.QLabel(self.frame_5)
        self.label_20.setObjectName("label_20")
        self.gridLayout_10.addWidget(self.label_20, 1, 0, 1, 1)
        self.spinBox_14 = QtWidgets.QSpinBox(self.frame_5)
        self.spinBox_14.setObjectName("spinBox_14")
        self.gridLayout_10.addWidget(self.spinBox_14, 1, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_5)
        self.label_19.setObjectName("label_19")
        self.gridLayout_10.addWidget(self.label_19, 1, 2, 1, 1)
        self.spinBox_12 = QtWidgets.QSpinBox(self.frame_5)
        self.spinBox_12.setObjectName("spinBox_12")
        self.gridLayout_10.addWidget(self.spinBox_12, 1, 3, 1, 1)
        self.spinBox_11 = QtWidgets.QSpinBox(self.frame_5)
        self.spinBox_11.setObjectName("spinBox_11")
        self.gridLayout_10.addWidget(self.spinBox_11, 5, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_5)
        self.label_18.setObjectName("label_18")
        self.gridLayout_10.addWidget(self.label_18, 5, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_5)
        self.label_12.setObjectName("label_12")
        self.gridLayout_10.addWidget(self.label_12, 5, 0, 1, 1)
        self.spinBox_13 = QtWidgets.QSpinBox(self.frame_5)
        self.spinBox_13.setObjectName("spinBox_13")
        self.gridLayout_10.addWidget(self.spinBox_13, 5, 3, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_5)
        self.gridLayout_6.addWidget(self.frame_4, 1, 0, 1, 1)
        self.general_Miscellaneous = CollapsablePanel(self.scrollAreaWidgetContents)
        self.general_Miscellaneous.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.general_Miscellaneous.setFrameShadow(QtWidgets.QFrame.Plain)
        self.general_Miscellaneous.setObjectName("general_Miscellaneous")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.general_Miscellaneous)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_23 = CollapsablePanelHeader(self.general_Miscellaneous)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_8.addWidget(self.label_23)
        self.line_6 = QtWidgets.QFrame(self.general_Miscellaneous)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_8.addWidget(self.line_6)
        self.frame_10 = CollapsablePanelContent(self.general_Miscellaneous)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_10.setObjectName("frame_10")
        self.formLayout = QtWidgets.QFormLayout(self.frame_10)
        self.formLayout.setContentsMargins(6, 6, 0, 0)
        self.formLayout.setHorizontalSpacing(6)
        self.formLayout.setVerticalSpacing(3)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.frame_10)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.general_colormap = QtWidgets.QComboBox(self.frame_10)
        self.general_colormap.setObjectName("general_colormap")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.general_colormap)
        self.label_2 = QtWidgets.QLabel(self.frame_10)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.general_rotate = QtWidgets.QComboBox(self.frame_10)
        self.general_rotate.setObjectName("general_rotate")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.general_rotate)
        self.verticalLayout_8.addWidget(self.frame_10)
        self.gridLayout_6.addWidget(self.general_Miscellaneous, 4, 0, 1, 1)
        self.general_DisplayOrder = CollapsablePanel(self.scrollAreaWidgetContents)
        self.general_DisplayOrder.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.general_DisplayOrder.setFrameShadow(QtWidgets.QFrame.Plain)
        self.general_DisplayOrder.setObjectName("general_DisplayOrder")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.general_DisplayOrder)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_22 = CollapsablePanelHeader(self.general_DisplayOrder)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_7.addWidget(self.label_22)
        self.line_5 = QtWidgets.QFrame(self.general_DisplayOrder)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_7.addWidget(self.line_5)
        self.frame_9 = CollapsablePanelContent(self.general_DisplayOrder)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_11.setContentsMargins(6, 6, 0, 0)
        self.gridLayout_11.setHorizontalSpacing(6)
        self.gridLayout_11.setVerticalSpacing(3)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.selectMaps_3 = QtWidgets.QListWidget(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.selectMaps_3.sizePolicy().hasHeightForWidth())
        self.selectMaps_3.setSizePolicy(sizePolicy)
        self.selectMaps_3.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.selectMaps_3.setObjectName("selectMaps_3")
        self.gridLayout_11.addWidget(self.selectMaps_3, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.frame_9)
        self.gridLayout_6.addWidget(self.general_DisplayOrder, 3, 0, 1, 1)
        self.frame_6 = CollapsablePanel(self.scrollAreaWidgetContents)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_21 = CollapsablePanelHeader(self.frame_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_6.addWidget(self.label_21)
        self.line_4 = QtWidgets.QFrame(self.frame_6)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_6.addWidget(self.line_4)
        self.frame_7 = CollapsablePanelContent(self.frame_6)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_5.setContentsMargins(6, 6, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(6)
        self.gridLayout_5.setVerticalSpacing(3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.general_map_selection = QtWidgets.QListWidget(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.general_map_selection.sizePolicy().hasHeightForWidth())
        self.general_map_selection.setSizePolicy(sizePolicy)
        self.general_map_selection.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.general_map_selection.setObjectName("general_map_selection")
        self.gridLayout_5.addWidget(self.general_map_selection, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.frame_7)
        self.gridLayout_6.addWidget(self.frame_6, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem, 5, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.commandTabs.addTab(self.generalOptions, "")
        self.mapOptions = QtWidgets.QWidget()
        self.mapOptions.setObjectName("mapOptions")
        self.gridLayout = QtWidgets.QGridLayout(self.mapOptions)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.mapOptions)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 977, 662))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_8.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.comboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_8.addWidget(self.comboBox, 0, 0, 1, 3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_3)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_4)
        self.gridLayout_8.addLayout(self.horizontalLayout_2, 5, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem1, 8, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_8.addWidget(self.lineEdit, 2, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        self.doubleSpinBox_2.setSpecialValueText("")
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.horizontalLayout.addWidget(self.doubleSpinBox_2)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout.addWidget(self.doubleSpinBox)
        self.gridLayout_8.addLayout(self.horizontalLayout, 4, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 4, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_8.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 5, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_8.addWidget(self.line, 1, 0, 1, 3)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_8.addWidget(self.label_9, 6, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_8.addWidget(self.comboBox_2, 6, 2, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.commandTabs.addTab(self.mapOptions, "")
        self.textInfoTab = QtWidgets.QWidget()
        self.textInfoTab.setObjectName("textInfoTab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.textInfoTab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.textConfigEdit = TextConfigEditor(self.textInfoTab)
        self.textConfigEdit.setObjectName("textConfigEdit")
        self.gridLayout_9.addWidget(self.textConfigEdit, 0, 0, 1, 1)
        self.commandTabs.addTab(self.textInfoTab, "")
        self.verticalLayout.addWidget(self.commandTabs)
        self.gridLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.plotLayout = QtWidgets.QVBoxLayout(self.gridLayoutWidget)
        self.plotLayout.setContentsMargins(-1, -1, -1, 0)
        self.plotLayout.setObjectName("plotLayout")
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout_2.setStretch(0, 1)
        MapsVisualizer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MapsVisualizer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MapsVisualizer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MapsVisualizer)
        self.statusbar.setObjectName("statusbar")
        MapsVisualizer.setStatusBar(self.statusbar)
        self.actionOpen_directory = QtWidgets.QAction(MapsVisualizer)
        self.actionOpen_directory.setObjectName("actionOpen_directory")
        self.actionQuit = QtWidgets.QAction(MapsVisualizer)
        self.actionQuit.setObjectName("actionQuit")
        self.actionExport = QtWidgets.QAction(MapsVisualizer)
        self.actionExport.setObjectName("actionExport")
        self.actionAbout = QtWidgets.QAction(MapsVisualizer)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExtra_plot_options = QtWidgets.QAction(MapsVisualizer)
        self.actionExtra_plot_options.setObjectName("actionExtra_plot_options")
        self.menuFile.addAction(self.actionOpen_directory)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MapsVisualizer)
        self.commandTabs.setCurrentIndex(0)
        self.actionQuit.triggered.connect(MapsVisualizer.close)
        QtCore.QMetaObject.connectSlotsByName(MapsVisualizer)

    def retranslateUi(self, MapsVisualizer):
        _translate = QtCore.QCoreApplication.translate
        MapsVisualizer.setWindowTitle(_translate("MapsVisualizer", "MDT - Maps Visualizer"))
        self.label_13.setText(_translate("MapsVisualizer", "Index"))
        self.label_14.setText(_translate("MapsVisualizer", "Dimension:"))
        self.label_16.setText(_translate("MapsVisualizer", "Slice index:"))
        self.label_15.setText(_translate("MapsVisualizer", "Volume:"))
        self.label_17.setText(_translate("MapsVisualizer", "Zoom"))
        self.label_20.setText(_translate("MapsVisualizer", "x:"))
        self.label_19.setText(_translate("MapsVisualizer", "y:"))
        self.label_18.setText(_translate("MapsVisualizer", "h:"))
        self.label_12.setText(_translate("MapsVisualizer", "w:"))
        self.label_23.setText(_translate("MapsVisualizer", "Miscellaneous"))
        self.label.setText(_translate("MapsVisualizer", "Colormap:"))
        self.label_2.setText(_translate("MapsVisualizer", "Rotate:"))
        self.label_22.setText(_translate("MapsVisualizer", "Display order"))
        self.label_21.setText(_translate("MapsVisualizer", "Map selection"))
        self.commandTabs.setTabText(self.commandTabs.indexOf(self.generalOptions), _translate("MapsVisualizer", "General"))
        self.label_10.setText(_translate("MapsVisualizer", "Scale:"))
        self.label_8.setText(_translate("MapsVisualizer", "Title:"))
        self.label_11.setText(_translate("MapsVisualizer", "Clipping:"))
        self.label_9.setText(_translate("MapsVisualizer", "Colormap:"))
        self.commandTabs.setTabText(self.commandTabs.indexOf(self.mapOptions), _translate("MapsVisualizer", "Maps"))
        self.commandTabs.setTabText(self.commandTabs.indexOf(self.textInfoTab), _translate("MapsVisualizer", "Textual"))
        self.menuFile.setTitle(_translate("MapsVisualizer", "&File"))
        self.menuAbout.setTitle(_translate("MapsVisualizer", "&Help"))
        self.actionOpen_directory.setText(_translate("MapsVisualizer", "&Open directory"))
        self.actionQuit.setText(_translate("MapsVisualizer", "&Quit"))
        self.actionQuit.setShortcut(_translate("MapsVisualizer", "Ctrl+Q"))
        self.actionExport.setText(_translate("MapsVisualizer", "&Export"))
        self.actionAbout.setText(_translate("MapsVisualizer", "&About"))
        self.actionExtra_plot_options.setText(_translate("MapsVisualizer", "&Extra plot options"))

from ..widgets import CollapsablePanel, CollapsablePanelContent, CollapsablePanelHeader, TextConfigEditor
from . import main_rc
