#!/usr/bin/env python

# This script was automatically generated by the MDT GUI. 
# 
# Generated on: 2017-05-15 22:19:25
# MDT version: 0.9.31
# Purpose: Generate a results figure 

import mdt

with open('/tmp/noddi_comparison.conf', 'r') as f:
    config = f.read()

mdt.write_view_maps_figure(
    '/tmp/noddi_comparison',
    '/tmp/noddi_comparison.png',
    config=config,
    width=1200,
    height=1000,
    dpi=100)

